password: ENC[AES256_GCM,data:vGgGnFV+iiTu5A==,iv:mKvAesUayZPHbTr9+zvauVWxCQuQ+KgcoEsLqz8g/q4=,tag:KpcPHl04ac7i9lmim0rOTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-16T22:28:23Z"
    mac: ENC[AES256_GCM,data:a6E9sBFBJcPDBLE3UgZTya6cyze52r16pVFCQzH1VyY6frmK9pkY24biKCLO0SA9gdRZtqPJ6KVQC140SbBt4lD5h+pYWKibZz9TIbomu4/DsqbUWI56YpEaAjcAw1iwu5c89r7LzZaW/LA7yOvcXTgvaw7SWuiZL9k7ywb0zh8=,iv:9hQlq47FGhWYiGAXfftWh/USmj4uJfgqMNv8u+dJxnM=,tag:ermP56dTlNQUmjrFMXI17g==,type:str]
    pgp:
        - created_at: "2024-04-16T22:28:07Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhF4D6jP5/TQ1sVkSAQdAjtDH/NbJzmjCJZCJO3m2FJ3EuYAIq2VUBJy1mWzM+How\r\nsL9h+Z0bjbyoVlS8rVg1VA/DStkXr2p/ayq51rUmT0e7b1O0uM0odHR2Xz4d0Sst\r\n1GgBCQIQrzZsciLbyeC/eAW9LKRR+7iqpQuLmGJrcF1VRqRvVo+ChFdkoOoYn4cg\r\nP+J/FsW9EZeX/ceSfh+xXxEjc+UDlgSDQsAOEIEWOlSn3TC1zb1oc6QdE47j515x\r\nH3dhBm10RX3bTQ==\r\n=hwyC\r\n-----END PGP MESSAGE-----"
          fp: 656B0DD1A1FA7AD9E7A31D7AC61BDA871FF3E3FC
    unencrypted_suffix: _unencrypted
    version: 3.8.1
