name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd app_python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          cd app_python
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          cd app_python
          pip install pytest
          pytest ./tests/test.py

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Test for vulnerabilities
        run: |
          cd app_python
          snyk test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_app:latest